config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'

  get 'categories/show'

  get 'categories/edit'

  get 'categories/new'

  get 'posts/index'

  get 'posts/show'

  get 'posts/edit'

  get 'posts/new'

  resources :posts
  resources :categories

end

app/models/categories.rb
class Categories < ActiveRecord::Base
  attr_accessible :name
  has_many :postses
end

app/models/posts.rb
class Posts < ActiveRecord::Base
  attr_accessible :title, :body, :category_id
  belongs_to :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @cateories = Categories.all
  end

  def show
  end

  def edit
  end

  def new
    @cateories = Categories.new

  end
  def create
    @cateories = Categories.create(params[:categories])
  end

  def update

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Posts.all
  end

  def show
    @posts = Posts.find(params[:id])
  end

  def edit
    @posts = Posts.find(params[:id])
  end


  def update
    @posts = Posts.find(params[:id])
    if @posts.update_attributes(params[:posts])
      redirect_to  posts_path , :notice => "Data has been updated successfully"
    else
      redirect_to "edit"
    end
  end

  def destroy
    @posts = Posts.find(params[:id])
    @posts.destroy
    redirect_to posts_path
  end

  def new
    @posts = Posts.new
    @cateories = Categories.all
  end

  def create
    @posts = Posts.create(params[:posts])
    redirect_to posts_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories</h1>
<% @cateories.each do |cat| %>
    <p><%= cat.name %></p></<br>
<%end%>
<%= link_to "Add new category", new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= form_for @cateories do |f| %>
    <%= f.label "Category Name", :name
        f.text_field :name

                             %>
    <%= f.submit "Add category", :method => :new %>

<%end%>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value|  %>
<%= value %>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @posts do |f| %>
  <p>  <%= f.label :title %></p><br>
    <P><%= f.text_field :title %></P><br>

    <p>  <%= f.label :body %></p><br>
    <P><%= f.text_area :body %></P><br>

    <p>  <%= f.label "category" %><p><br>
    <p><%= f.select :category_id, Categories.all.collect { |x| [x.name,x.id] },{:include_blank => "select one"} %></p>

    <p><%= f.submit "update post" %></p>
<%end %>

app/views/posts/index.html.erb
<h1>Post</h1>
<% @posts.each do |post|   %>
<h2><%= link_to post.title,post %></h2>
<h2><%= post.body %></h2>
<hr>
<% end %>

<p><%= link_to "Add new", new_post_path %></p>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @posts do |f| %>
    <p>  <%= f.label :title %></p><br>
    <P><%= f.text_field :title %></P><br>

    <p>  <%= f.label :body %></p><br>
    <P><%= f.text_area :body %></P><br>

    <p>  <%= f.label "category" %><p><br>
    <p><%= f.select :category_id, Categories.all.collect { |x| [x.name,x.id] },{:include_blank => "select one"} %></p>

    <p><%= f.submit "Add post" %></p>
<%end %>

app/views/posts/show.html.erb
<h1>Posts show</h1>
<p><%= @posts.title %></p>
<p><%= @posts.created_at %></p>
<p><%= @posts.body %></p>
<%= link_to "Edit", edit_post_path %> | <%= link_to "Delete", @post, :confirm => "are you sure you want to delete?",:method => :delete  %>